on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

env:
  PACKAGE_NAME: '[[packageName]]'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION}
      - name: Push
        run: dotnet nuget push ${{ env.PACKAGE_NAME }}/bin/Release/${{ env.PACKAGE_NAME }}.${VERSION}.nupkg --source https://nuget.pkg.github.com/SpaceBank/index.json --api-key ${{ secrets.NUGET_SECRET_GITHUB }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_SECRET_GITHUB }}